# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm i
     
    - run: npm i --prefix frontend
    - run: CI='' npm run build --if-present
    - run: npm stop 
    - run: npm start
      env:
        NODE_ENV: ${{secrets.NODE_ENV}}
        PORT: ${{secrets.PORT}}
        MONGO_URI: ${{secrets.MONGO_URI}}
        PAYPAL_CLIENT_ID: ${{secrets.PAYPAL_CLIENT_ID}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        Access_Key_ID: ${{secrets.Access_Key_ID}}
        Access_Secret_Key: ${{secrets.Access_Secret_Key}}  
